# Generated by Django 4.1.7 on 2023-05-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AlterField(
            model_name='product',
            name='link',
            field=models.TextField(max_length=200),
        ),
    ]
